PROMPT_BATTERY_STATUS=${PROMPT_BATTERY_STATUS:-1}
PROMPT_POWERLINE=${PROMPT_POWERLINE:-1}
PROMPT_POWERLINE_ALIASES='~/src=SRC,~/projects=PROJS,~/cfg=CFG,~/src/ansible=ANSIBLE,~/src/ansible/roles=ANSIBLE ROLES'
